id = "horizon-extended"
name = "Horizon Extended"
version = "0.0.1"
schema_version = 1
authors = ["lancewilhelm <lance.wilhelm@gmail.com>"]
description = "Brining over the mildly popular Horizon Extended theme from VSCode and Neovim"
repository = "https://github.com/lancewilhelm/horizon-extended.zed.git"
